import type { Service } from "./de";
import { faqCategoriesEn } from "./faq-categories";

export const en = {
  // @NEXIFYAI-MARKER: prelogin-content-trust-20260713
  common: {
    cta: "Start your project",
    ctaSecondary: "View services",
    learnMore: "Learn more",
    from: "from",
    workdays: "working days",
    workday: "working day",
    netPerDay: "€ 449 net / working day",
    allServices: "All services",
  },
  home: {
    badge: "AI-assisted development · German & Dutch · For businesses",
    titleA: "Digital excellence.",
    titleB: "In days, not months.",
    subtitle:
      "NeXify AI develops premium websites, online shops, web apps and AI automations – personally led by a skilled professional, accelerated by appropriate AI tools, transparent at a fixed daily rate of € 449 net.",
    ctaPrimary: "Free initial consultation",
    ctaSecondary: "Explore services",
    stats: [
      { value: "€ 449", label: "net per working day – transparently calculated" },
      { value: "1–3", label: "guide value for clearly scoped websites" },
      { value: "1", label: "single point of contact from concept to handover" },
      { value: "Chat", label: "AI advisor for an initial assessment" },
    ],
    pillarsEyebrow: "Why NeXify AI",
    pillarsTitle: "One professional. Modern AI. Measurable results.",
    pillars: [
      {
        icon: "Code2",
        title: "One professional, one result",
        text: "No handover chain between sales, design, development and QA. Concept, architecture, implementation and quality control are in one pair of hands – personal and transparent.",
      },
      {
        icon: "Bot",
        title: "AI-assisted, not AI-outsourced",
        text: "Modern AI tools accelerate research, implementation and testing. The technical decisions remain with an experienced developer – with full accountability.",
      },
      {
        icon: "ChartNoAxesCombined",
        title: "Transparency per working day",
        text: "€ 449 net per working day. Scope, assumptions and additional requirements are made visible before implementation – you retain full cost control at all times.",
      },
    ],
    servicesEyebrow: "Services",
    servicesTitle: "From the first click to a scaled platform",
    servicesText: "Eight clearly defined service modules – each with a time range, clear deliverables and a transparent daily rate.",
    processEyebrow: "Approach",
    processTitle: "Five steps. Zero surprises.",
    quotesEyebrow: "Testimonials & results",
    quotesTitle: "What working with NeXify AI means",
    ctaBandTitle: "Ready for your project?",
    ctaBandText:
      "Describe your project – you will typically receive an honest assessment with effort range and price bracket within one working day. Or ask NeXify AI, our AI advisor, directly in the chat.",
    ctaBandBtn: "Send enquiry now",
    ctaBandBtn2: "Chat with NeXify AI",
    ctaBandWissen: "Knowledge & insights",
    marquee: ["Next.js", "React", "TypeScript", "Supabase", "AI agents", "Automation", "E-commerce", "Web apps", "Mobile apps", "SEO", "Cloud infrastructure", "API integration"],
    githubProof: {
      eyebrow: "Open source & transparency",
      title: "Engineering you can inspect",
      text:
        "Our agency platform and website are documented publicly on GitHub — Next.js, FastAPI, TypeScript. No black box: stack, topics and delivery promises are visible. Project outcomes stay anonymised (see references).",
      repoCta: "GitHub repository",
      casesCta: "View anonymised cases",
      items: [
        { value: "Next.js", label: "Agency site & delivery stack" },
        { value: "FastAPI", label: "Backend & integrations" },
        { value: "€ 449", label: "net / day — publicly priced" },
        { value: "DACH+NL", label: "B2B focus, based in Venlo" },
      ],
    },
  },
  services: [
    {
      slug: "landingpages",
      icon: "LayoutTemplate",
      title: "Landing pages that sell with clarity",
      shortTitle: "Landing page",
      eyebrow: "Clear. Fast. Conversion-oriented.",
      description:
        "A focused page for an offer, a campaign or a market launch – conceived, designed, developed and delivered technically sound. From the first wireframe to going live, you get a page that understands visitors, guides them and converts.",
      promise: "A sales-ready landing page in one working day.",
      days: "1 working day",
      minDays: 1,
      maxDays: 1,
      features: ["Premium UI/UX in your corporate design", "Responsive across all devices", "Contact or lead form", "Technical SEO & metadata", "Performance optimisation (Core Web Vitals)", "Legally required links"],
      deliverables: ["Strategic page structure", "Bespoke premium design", "Next.js implementation", "Form integration with email connection", "QA on desktop and mobile"],
      idealFor: ["New offers", "Campaigns", "Lead generation", "Product validation"],
    },
    {
      slug: "websites",
      icon: "Globe2",
      title: "Business websites with substance",
      shortTitle: "Business website",
      eyebrow: "Brand, trust and demand in one system.",
      description:
        "A complete B2B business website with clear positioning, service pages, contact funnel, SEO foundation and all required standard pages. Strategy, content and technology are conceived together – for a website that generates enquiries rather than simply existing.",
      promise: "A complete website in two to three working days.",
      days: "2–3 working days",
      minDays: 2,
      maxDays: 3,
      features: ["Strategy and information architecture", "Home and service pages", "About us / expert profile", "Pricing and process overview", "Contact funnel with form", "Legal pages (imprint, privacy policy, terms)"],
      deliverables: ["Next.js App Router architecture", "Bespoke design system", "SEO metadata and sitemap", "Responsive QA", "Deployment preparation"],
      idealFor: ["Agencies", "Consultancies", "Trades and SMEs", "B2B service providers"],
    },
    {
      slug: "onlineshops",
      icon: "ShoppingCart",
      title: "Online shops that grow with your product range",
      shortTitle: "Online shop",
      eyebrow: "Fast shopping. Clean data. Clear processes.",
      description:
        "From a focused shop to a comprehensive commerce system: product search, categories, checkout, payments, inventory management and automations are planned to fit your operations. It's not the off-the-shelf builder that defines the shop – your business model does.",
      promise: "Standard shops in six to eight days, large catalogues from twelve days.",
      days: "6–8 working days",
      minDays: 6,
      maxDays: 8,
      features: ["Product and category structure", "Search and filters", "Checkout and payment providers", "Order communication via email", "SEO and structured data", "Interfaces and product import"],
      deliverables: ["Shop frontend", "Administration logic", "Product import", "Checkout tests", "Operations and handover documentation"],
      idealFor: ["D2C and B2B commerce", "Niche retail", "Manufacturers", "Ranges of up to ~50,000 products"],
    },
    {
      slug: "enterprise-commerce",
      icon: "Boxes",
      title: "Commerce platforms for 50,000+ products",
      shortTitle: "Enterprise commerce",
      eyebrow: "Catalogues, search, integrations and operations for large data volumes.",
      description:
        "For large product ranges, the data model, search index, import pipeline, caching, product variants, ERP/PIM integration and operational monitoring are designed for scale from the outset. Performance and data quality are not retrofits here – they are architectural principles.",
      promise: "Large shops start from twelve working days – the scope follows the real system complexity.",
      days: "from 12 working days",
      minDays: 12,
      from: true,
      features: ["50,000+ products at high performance", "High-performance search and facets", "PIM/ERP/feed integration", "Batch and delta imports", "Cache and index strategy", "Monitoring and recovery"],
      deliverables: ["Technical blueprint", "Import and search architecture", "Scalable shop", "Load and data quality tests", "Operations manual"],
      idealFor: ["Wholesale", "Spare parts retail", "Multi-brand shops", "Catalogue-based platforms"],
    },
    {
      slug: "web-apps",
      icon: "AppWindow",
      title: "Web apps for real business operations",
      shortTitle: "Web app",
      eyebrow: "Portals, dashboards and process software.",
      description:
        "Bespoke web applications for customer portals, internal processes, booking, scheduling, documents, workflows or industry-specific operations. Software that adapts to your business – not the other way round.",
      promise: "Compact MVPs in six to eight days, complex systems from twelve days.",
      days: "6–8 working days",
      minDays: 6,
      maxDays: 8,
      features: ["Login and role-based access", "Dashboards and analytics", "Data models and APIs", "Workflows and notifications", "File and document management", "Auditable states"],
      deliverables: ["Product concept", "Responsive web app", "Backend/API", "Tests", "Deployment and operations handover"],
      idealFor: ["Customer portals", "SaaS MVPs", "Internal tools", "Booking and service platforms"],
    },
    {
      slug: "mobile-apps",
      icon: "Smartphone",
      title: "Mobile apps with a shared product core",
      shortTitle: "Mobile app",
      eyebrow: "Cross-platform, maintainable and focused on the use case.",
      description:
        "Mobile applications are developed as focused products – with a shared design system for iOS and Android, clean API integration and a clear publication strategy for the app stores.",
      promise: "Compact cross-platform MVPs in six to eight days, comprehensive apps from twelve days.",
      days: "6–8 working days",
      minDays: 6,
      maxDays: 8,
      features: ["iOS and Android from a single codebase", "Cross-platform architecture", "Authentication", "Push and notifications", "Offline/sync concept", "Store preparation"],
      deliverables: ["Product flow", "App interface", "API integration", "Device testing", "Release checklist"],
      idealFor: ["Service apps", "Field service", "Customer loyalty", "Mobile process support"],
    },
    {
      slug: "automatisierung",
      icon: "Workflow",
      title: "AI-assisted automation with control",
      shortTitle: "Automation",
      eyebrow: "Less routine. More transparent operations.",
      description:
        "Recurring tasks are analysed, standardised and automated with suitable workflows, integrations and AI-assisted steps. Every automated process remains measurable, documented and controllable.",
      promise: "Not automate as much as possible – but the right things, measurably and under control.",
      days: "from 1 working day",
      minDays: 1,
      from: true,
      features: ["Process analysis", "Email and document flows", "CRM/ERP integrations", "Approvals and policy gates", "Monitoring", "Error and recovery paths"],
      deliverables: ["Process map", "Automated workflow", "Test cases", "Monitoring", "Operations documentation"],
      idealFor: ["Sales", "Support", "Back office", "Project and data processes"],
    },
    {
      slug: "ai-agenten",
      icon: "Bot",
      title: "AI agents for clearly defined tasks",
      shortTitle: "AI agents",
      eyebrow: "Tools, rules and evidence instead of uncontrolled chatbots.",
      description:
        "Agentic solutions are given clear roles, data access rights, approvals, tests and logs. This produces reliable assistants and operators instead of demo chats – like NeXify AI, the AI advisor on this website.",
      promise: "AI supports the work – technical accountability, boundaries and control remain visible.",
      days: "from 3 working days",
      minDays: 3,
      from: true,
      features: ["Roles and permissions", "Knowledge access (RAG)", "Tool and API integration", "Approval stages", "Evaluation", "Evidence and monitoring"],
      deliverables: ["Agent profile", "Tool and knowledge integration", "Security rules", "Test suite", "Operations concept"],
      idealFor: ["Knowledge work", "Support", "Research", "Internal operations"],
    },
  ] as Service[],
  servicesPage: {
    eyebrow: "Services",
    title: "Eight modules. One standard: excellence.",
    intro:
      "Every service has a clear time range, defined deliverables and a transparent price of € 449 net per working day. What you read here is what you get – no fine print, no agency overhead.",
    featuresLabel: "Scope of services",
    deliverablesLabel: "You receive",
    idealLabel: "Ideal for",
  },
  pricing: {
    eyebrow: "Pricing",
    title: "One rate. Full transparency.",
    intro:
      "€ 449 net per working day – this rate applies to every service, every project, every day. A working day comprises up to eight plannable specialist hours for concept, design, development, testing and documentation.",
    dayRateTitle: "The daily rate",
    dayRateText:
      "Before the project begins, you receive a reliable effort range in working days. A binding fixed total price is possible once scope, content, integrations and acceptance criteria are clearly defined. Additional requirements are always flagged before execution – never after.",
    includedTitle: "Included in the working day",
    included: [
      "Concept and information architecture",
      "Bespoke design within the design system",
      "Development (frontend, backend, APIs)",
      "Integrations and data connectivity",
      "Testing, QA and mobile verification",
      "Documentation and handover",
    ],
    notIncludedTitle: "Not included (unless agreed)",
    notIncluded: ["Hosting and domain costs", "Licences and external API costs", "Payment provider fees", "Stock material and content creation", "Ongoing maintenance contracts (bookable separately)"],
    calcTitle: "Project cost calculator",
    calcText: "Select a service and the expected scope – you will see the realistic investment immediately.",
    calcService: "Service",
    calcDays: "Working days",
    calcNet: "Net investment",
    calcVat: "plus 21% VAT",
    calcGross: "Gross (incl. VAT)",
    calcNote: "For cross-border B2B services within the EU, the reverse charge procedure may apply with a valid VAT ID – in which case no VAT is charged.",
    vatNote: "All prices net plus applicable VAT. B2B only.",
  },
  process: {
    eyebrow: "Approach",
    title: "Five steps from idea to operation",
    intro:
      "A standardised process ensures that suitable projects are delivered in days rather than months – with clear quality checks, no surprises and full transparency at every step.",
    steps: [
      { n: "01", icon: "ChartNoAxesCombined", title: "Goal and business value", text: "We clarify which outcome matters, who will use it and what is deliberately not part of the initial scope. Focus beats feature lists." },
      { n: "02", icon: "MessageSquareMore", title: "Concept and fixed price range", text: "The effort is stated in working days. You see scope, price bracket, assumptions and possible extensions up front – in writing and binding." },
      { n: "03", icon: "Code2", title: "AI-assisted implementation", text: "Modern development and testing tools accelerate analysis, design, code, tests and documentation – under continuous expert guidance." },
      { n: "04", icon: "Settings2", title: "Testing and acceptance", text: "Functionality, presentation, mobile view, forms, performance and key user journeys are verifiably tested and documented." },
      { n: "05", icon: "Rocket", title: "Handover and further development", text: "You receive code, documentation, clear operational information and a prioritised list of sensible next steps." },
    ],
    promiseTitle: "What you can rely on",
    promises: [
      { title: "Response within 24h", text: "Every enquiry receives a personal, qualified response within one working day." },
      { title: "Written scope clarity", text: "No project starts without documented scope, assumptions and price bracket." },
      { title: "Daily visibility", text: "On multi-day projects, you see progress – not just at the end." },
      { title: "Clean handover", text: "Code, access credentials, documentation and operational notes belong to you. No vendor lock-in." },
    ],
  },
  platform: {
    eyebrow: "Platform & technology",
    title: "The tech stack behind the speed",
    intro:
      "Speed without sacrificing quality comes from a deliberately curated and proven technology stack – combined with appropriate AI-assisted development and testing tools.",
    blocks: [
      {
        icon: "Layers",
        title: "Frontend & design",
        text: "Modern, maintainable interfaces with first-class performance and accessibility.",
        points: ["Next.js App Router & React", "TypeScript throughout", "Bespoke design systems", "Core Web Vitals optimised", "Responsive & accessible"],
      },
      {
        icon: "Database",
        title: "Backend & data",
        text: "Scalable APIs and data models that grow with your business.",
        points: ["Supabase / PostgreSQL", "REST & streaming APIs", "Authentication & roles", "Data import pipelines", "Backups & monitoring"],
      },
      {
        icon: "Bot",
        title: "AI & agents",
        text: "Production-ready AI integrations with control, logs and approvals.",
        points: ["GPT, Claude & Gemini integration", "RAG knowledge connectivity", "AI advisors like NeXify AI", "Quotation & email automation", "Evaluation & guardrails"],
      },
      {
        icon: "ShieldCheck",
        title: "Operations & security",
        text: "Reliable operations with clear responsibilities and GDPR compliance.",
        points: ["Vercel & self-hosting (Docker/Traefik)", "Cloudflare CDN & protection", "SSL, security headers, hardening", "GDPR-compliant data flows", "Transactional emails (Resend)"],
      },
    ],
    novaTitle: "NeXify AI – your AI advisor on this website",
    novaText:
      "What you experience in the chat at the bottom right is an example of our AI agent service: NeXify AI advises visitors in two languages, qualifies enquiries, creates structured quotations and sends them automatically by email – including follow-ups. We build the same technology for your business.",
    novaBtn: "Try NeXify AI now",
  },
  references: {
    eyebrow: "References & results",
    title: "Results that speak for themselves",
    intro:
      "Selected, anonymised project results from the web, commerce and automation space. On request, we are happy to provide suitable reference contacts.",
    cases: [
      {
        tag: "B2B website",
        title: "Consultancy firm, DACH",
        text: "Complete business website with service architecture, SEO foundation and contact funnel – conceived and live in three working days.",
        results: ["3 working days to go-live", "+68% organic enquiries in 90 days", "Load time under 1 second"],
      },
      {
        tag: "E-commerce",
        title: "Spare parts retailer, Netherlands",
        text: "Commerce platform with 60,000+ products, faceted search, ERP integration and automated delta imports.",
        results: ["60,000+ products at high performance", "Search responses under 150 ms", "Import process fully automated, daily"],
      },
      {
        tag: "AI automation",
        title: "Mid-sized service provider",
        text: "Automated quotation and email pipeline with AI pre-qualification of incoming enquiries and CRM integration.",
        results: ["–70% manual processing time", "Response time from 2 days to 2 hours", "Fully logged workflow"],
      },
    ],
    quotes: [
      {
        quote: "Within three days we had a website that agencies had quoted us three months for – of better quality and at a fraction of the price.",
        author: "Managing Director, Consultancy (DACH)",
      },
      {
        quote: "The combination of personal accountability and AI speed is impressive. Every commitment was kept, every effort was made transparent up front.",
        author: "Owner, Trading Company (NL)",
      },
      {
        quote: "Finally someone who doesn't sell automation as a buzzword, but implements it as a controlled, measurable process.",
        author: "Head of Operations, Service Provider (DE)",
      },
    ],
  },
  wissen: {
    eyebrow: "Knowledge",
    title: "Insights into AI-assisted development",
    intro: "Practical knowledge on websites, commerce, automation and AI agents – no marketing fog, just clear recommendations.",
    readMore: "Read more",
    readLess: "Collapse",
    cta: {
      title: "From insight to a concrete project?",
      text: "Free initial consultation — effort range and price bracket typically within one working day. Daily rate € 449 net, personally accountable.",
      primary: "Request a project",
      secondary: "Services & pricing",
    },
    articles: [
      {
        tag: "Strategy",
        readTime: "4 min.",
        title: "Why a website in 3 days can be better than one in 3 months",
        excerpt: "Long project timelines rarely arise from quality – usually from handovers, coordination loops and idle time.",
        body: [
          "The classic agency process has many stations: sales, strategy, design, development, QA, project management. Every handover costs time, information and money. The result does not get better – just more expensive and later.",
          "AI-assisted development flips the model: one experienced professional steers the entire process and uses AI tools for research, code, testing and documentation. Throughput time drops from months to days, while quality control remains in one pair of hands.",
          "Standardisation is the key: proven architectures, reusable design systems and automated checks. When you've walked every step a hundred times, you walk it faster and more confidently.",
        ],
      },
      {
        tag: "E-commerce",
        readTime: "5 min.",
        title: "50,000 products are not a frontend problem – they're a data problem",
        excerpt: "Large catalogues rarely fail on looks. They fail on imports, search and data quality.",
        body: [
          "Anyone planning a shop with large product ranges should talk about data flows first: where does product master data come from? How often do prices and stock levels change? Which systems (ERP, PIM, supplier feeds) need to be connected?",
          "The answer determines the architecture: batch and delta imports, a performant search index with facets, consistent caching and monitoring that detects data errors before customers see them.",
          "A shop that thinks through these fundamentals from day one scales comfortably from 5,000 to 100,000 products. One that has to retrofit them becomes a never-ending project.",
        ],
      },
      {
        tag: "AI agents",
        readTime: "6 min.",
        title: "From chatbot to sales agent: what makes NeXify AI different",
        excerpt: "Most website chatbots answer FAQs. A real AI agent qualifies, advises and creates quotations.",
        body: [
          "A classic chatbot is a search box with a speech bubble. An AI agent, by contrast, has a role, a goal and tools: it knows the service portfolio, calculates prices transparently, asks qualification questions and ultimately produces a structured quotation.",
          "NeXify AI – the advisor on this website – demonstrates the principle live: the conversation is saved, the quotation is sent by email, and after 24 hours a friendly follow-up is automatically triggered. An anonymous visitor becomes a documented lead.",
          "The guardrails are what matter: no invented promises, clear pricing logic, logging of every interaction. AI in sales only works with control – but then it works exceptionally well.",
        ],
      },
      {
        tag: "Automation",
        readTime: "4 min.",
        title: "The right order of automation",
        excerpt: "Not everything that can be automated should be automated. A prioritisation guide.",
        body: [
          "The best starting point is processes that are frequent, rule-based and annoying: quotation documents, email routing, data transfer between systems, report generation. Here the return is immediately measurable.",
          "Next come processes with AI support: pre-qualification of enquiries, summaries, draft creation. Here a human remains in the approval loop – AI accelerates but does not decide alone.",
          "Finally, complex agentic workflows. Those who have built the first two stages properly have the data quality and process clarity that make stage three possible in the first place.",
        ],
      },
      {
        tag: "Technology",
        readTime: "5 min.",
        title: "Next.js, Supabase & co.: why this stack",
        excerpt: "Technology decisions are operating cost decisions. A rationale for the NeXify stack.",
        body: [
          "Next.js delivers server rendering, excellent SEO and an ecosystem supported from startups to enterprises. React and TypeScript ensure maintainability and developer availability for years.",
          "Supabase combines PostgreSQL – the most reliable open-source database – with authentication, storage and real-time features. This drastically reduces integration effort without leading to proprietary dependency.",
          "The principle: technology follows operations. Every component must remain replaceable, data must be exportable, and the customer always receives the complete code.",
        ],
      },
      {
        tag: "Legal & compliance",
        readTime: "5 min.",
        title: "GDPR-compliant AI integration: the checklist",
        excerpt: "AI features and data protection are not mutually exclusive – when the fundamentals are in place.",
        body: [
          "First: data minimisation. Only what is necessary for the purpose is transmitted to AI services. Personal data is pseudonymised where possible or avoided entirely.",
          "Second: transparency. Users are informed when they interact with an AI system, what is stored and for what purpose. This website demonstrates this with the AI notice and the privacy policy.",
          "Third: data processing agreements and storage locations. Processors are contractually bound (DPA), transfers to third countries are reviewed, deletion deadlines are defined. Those who document this integrate AI in a legally compliant manner.",
        ],
      },
    ],
  },
  faqPage: {
    eyebrow: "FAQ",
    title: "Frequent questions, honest answers",
    intro:
      "Comprehensive answers on NeXify AI, services, pricing, AI agents, privacy, onboarding and the Venlo office — for decision-makers in DACH. Missing a question? Chat, contact form or project planner help immediately.",
    ctaTitle: "Still open? Let's get concrete.",
    ctaText:
      "Personal assessment within one working day — or immediate orientation via chat and the project planner.",
    ctaContact: "Contact us",
    ctaPlanner: "Plan a project",
    ctaServices: "Services",
    ctaPricing: "Pricing",
    ctaKnowledge: "Knowledge",
  },
  faqCategories: faqCategoriesEn,
  about: {
    eyebrow: "About me",
    title: "Pascal Courbois – the professional behind NeXify AI",
    intro: "German from the Limburg border region, at home in the Netherlands for over five years – with more than 20 years of professional and practical experience in IT, commerce and sales. A single point of contact for strategy, design, development and operations.",
    paragraphs: [
      "I am Pascal Courbois – German from the Limburg border region, married to a Dutch woman and at home in the Netherlands for a good five years. I live and work daily in both cultures and languages. For you, that means: advice, quotations and communication in German or Dutch – without translation losses and with genuine understanding of both markets.",
      "In more than 20 years of professional and practical experience, I have come to know both sides of digitalisation: the technical side in IT and programming – and the entrepreneurial side in business and commerce. Add to that years of sales experience, including at Telekom Deutschland, Vodafone and Postcon Deutschland. I therefore not only know how software is built, but also how customers think, how processes in companies really work and what causes projects to fail in practice – and it is precisely this understanding that flows into every project.",
      "NeXify AI is the answer to a simple observation: most digital projects are too expensive, take too long and lose quality between the departments of an agency. As an experienced developer and consultant, I bring together concept, architecture, implementation and quality control in one pair of hands.",
      "State-of-the-art AI tools – the same ones behind NeXify AI – accelerate research, code, testing and documentation many times over. This produces results in days that classic processes need months for. The technical accountability always remains with me personally.",
      "I work from Venlo for companies in Germany, Austria, Switzerland and the Netherlands – in German and Dutch, exclusively B2B, always with a transparent daily rate and written scope clarity before the project begins.",
    ],
    facts: [
      { label: "Origin", value: "German · Limburg border region" },
      { label: "Location", value: "Venlo, Netherlands (5+ years)" },
      { label: "Experience", value: "20+ years IT, commerce & sales" },
      { label: "Languages", value: "German, Dutch, English" },
      { label: "Market", value: "DE · AT · CH · NL" },
      { label: "Model", value: "B2B, € 449 net/day" },
    ],
    journeyTitle: "Experience you can feel",
    journeyIntro: "More than 20 years of practice – technical, commercial and in sales. This combination is rare and makes the difference between a website and a tool that sells.",
    journey: [
      { title: "IT & development", text: "Over two decades of practice in IT and programming – from solid systems to modern AI architectures. Technology is not a black-box promise for me, but a craft with accountability." },
      { title: "Commercial practice", text: "Costing, processes, responsibility: I have worked commercially myself and know how decisions are made in companies – and what an investment really needs to justify." },
      { title: "Enterprise-level sales", text: "Years of sales experience including at Telekom Deutschland, Vodafone and Postcon Deutschland. I understand target audiences, customer needs and how interest becomes measurable revenue." },
      { title: "Two countries, one region", text: "As a German in the Netherlands, married to a Dutch woman, I combine both business cultures – ideal for companies in the German-Dutch economic region." },
    ],
    principlesTitle: "My working principles",
    principles: [
      { title: "Honesty over revenue", text: "If a project doesn't make sense, I say so – including cheaper alternatives." },
      { title: "Results over effort", text: "What is billed is what delivers results. Idle time and meeting marathons are not your problem." },
      { title: "Ownership with the customer", text: "Code, data, access credentials and documentation belong to you. In full, from day one." },
      { title: "Controlled AI", text: "AI accelerates my work, but never replaces review, accountability and approval by the professional." },
    ],
  },
  contact: {
    eyebrow: "Contact",
    title: "Tell me about your project",
    intro: "You will receive a personal, qualified response within one working day with an honest assessment and effort range. Alternatively, the NeXify AI chat will advise you immediately – around the clock.",
    name: "Your name *",
    email: "Email address *",
    companyField: "Company",
    phone: "Phone (optional)",
    message: "Your project *",
    messagePlaceholder: "What would you like to build? Website, shop, app, automation … The more specific, the more precise the assessment.",
    submit: "Send enquiry",
    sending: "Sending …",
    success: "Thank you! Your enquiry has been received – you will shortly receive a confirmation by email and a personal response from Pascal usually within one working day.",
    error: "Sending failed. Please try again or write directly to",
    directTitle: "Direct line",
    responseTitle: "Response time",
    responseText: "Target: personal reply within one working day — often sooner. Honest target, not a fake SLA.",
    b2bNote: "Exclusively B2B: quotations are directed at companies, self-employed professionals and organisations.",
  },
};

export type Dict = typeof en;
