import { company } from "@/lib/site-data";
import type { LegalPage } from "@/lib/legal-content";

const related = {
  impressum: [
    { label: "Privacy", href: "/datenschutz" },
    { label: "Terms", href: "/agb" },
    { label: "DPA", href: "/avv" },
    { label: "Withdrawal", href: "/widerruf" },
    { label: "Cookies", href: "/cookie-richtlinie" },
    { label: "AI Notice", href: "/ki-hinweise" },
  ],
  datenschutz: [
    { label: "Imprint", href: "/impressum" },
    { label: "Cookies", href: "/cookie-richtlinie" },
    { label: "DPA", href: "/avv" },
    { label: "AI Notice", href: "/ki-hinweise" },
  ],
  agb: [
    { label: "Imprint", href: "/impressum" },
    { label: "Privacy", href: "/datenschutz" },
    { label: "DPA", href: "/avv" },
    { label: "Withdrawal", href: "/widerruf" },
  ],
  avv: [
    { label: "Privacy", href: "/datenschutz" },
    { label: "Terms", href: "/agb" },
  ],
  widerruf: [
    { label: "Terms", href: "/agb" },
    { label: "Imprint", href: "/impressum" },
  ],
  "cookie-richtlinie": [
    { label: "Privacy", href: "/datenschutz" },
    { label: "Imprint", href: "/impressum" },
  ],
  "ki-hinweise": [
    { label: "Privacy", href: "/datenschutz" },
    { label: "Terms", href: "/agb" },
  ],
} as const;

export const legalPagesEn: Record<string, LegalPage> = {
  impressum: {
    slug: "impressum",
    title: "Legal Notice (Impressum)",
    intro: "Provider identification aligned with §§ 5, 6 German DDG for a Dutch eenmanszaak targeting the DACH market.",
    updated: "2 August 2026",
    related: [...related.impressum],
    sections: [
      { id: "company", heading: "1. Company", paragraphs: [`${company.legalName}`, `${company.legalForm} under Dutch law, Owner: ${company.owner}`, `${company.address}, ${company.postalCity}, ${company.country}`] },
      { id: "contact", heading: "2. Contact", paragraphs: [`Email: ${company.email}`, `Phone: ${company.phone}`, `Web: ${company.website}`] },
      { id: "register", heading: "3. Registration & tax", paragraphs: [`KvK: ${company.kvk}`, `VAT ID: ${company.vatId}`, "[BITTE ERGÄNZEN: RSIN (falls separat auszuweisen) / Handelsregisterauszug-Datum der letzten Prüfung]", "Scope: IT consulting, AI automation, software and web development (B2B)."] },
      { id: "rep", heading: "4. Representation", paragraphs: [`${company.owner}, Owner / Director. Editorial responsibility: ${company.owner}.`] },
      { id: "ddg", heading: "5. Applicable law & DDG", paragraphs: ["Dutch commercial law applies (KvK). Where the offering targets Germany, §§ 5, 6 DDG information duties are fulfilled voluntarily.", "Lead supervisory authority for privacy: Autoriteit Persoonsgegevens (NL)."] },
      { id: "ins", heading: "6. Professional liability", paragraphs: ["[BITTE ERGÄNZEN: Berufshaftpflichtversicherung – Versicherer, Police-Nr., räumlicher Geltungsbereich, Deckungssumme]"] },
      { id: "b2b", heading: "7. B2B only", paragraphs: ["Offers are exclusively for businesses and comparable organisations. No consumer contracts."] },
      { id: "liab", heading: "8. Liability", paragraphs: ["Content is prepared with care. Binding offers are only those confirmed in writing."] },
      { id: "dispute", heading: "9. Consumer ADR", paragraphs: [`No participation in consumer ADR. Contact: ${company.email}.`] },
    ],
  },
  datenschutz: {
    slug: "datenschutz",
    title: "Privacy Policy",
    intro: "GDPR Articles 12–14 information for website, AI chat and B2B inquiries.",
    updated: "2 August 2026",
    related: [...related.datenschutz],
    sections: [
      { heading: "1. Controller", paragraphs: [`${company.legalName}, ${company.address}, ${company.postalCity}, ${company.country}. Contact: ${company.email}, ${company.phone}.`] },
      { heading: "2. Data Protection Officer", paragraphs: [`No DPO is currently appointed under Art. 37 GDPR. Privacy requests: ${company.email}.`, "[BITTE ERGÄNZEN: Bestätigung, ob künftig ein externer DSB bestellt wird / Kontaktdaten falls vorhanden]"] },
      { heading: "3. Legal bases (Art. 6)", bullets: ["Consent (Art. 6(1)(a)) – optional cookie categories", "Contract / pre-contract (Art. 6(1)(b))", "Legal obligation (Art. 6(1)(c))", "Legitimate interests (Art. 6(1)(f)) – security, B2B communication"] },
      { heading: "4. Hosting & logs", paragraphs: ["IP, timestamp, resource, referrer, device data for delivery and abuse prevention. CDN/hosting providers under Art. 28 where required."] },
      { heading: "5. Contact & chat", paragraphs: ["Inquiry and chat data processed for response and pre-contractual communication. No Art. 22 solely automated decisions."] },
      { heading: "6. Recipients & transfers", paragraphs: ["Hosting, email, AI/memory providers; third-country transfers only with appropriate safeguards (e.g. SCCs)."] },
      { heading: "7. Retention", paragraphs: ["As long as needed for the purpose; accounting data typically 7 years (NL)."] },
      { heading: "8. Rights", bullets: ["Access, rectification, erasure, restriction, portability, objection, withdraw consent, lodge complaint with Autoriteit Persoonsgegevens"] },
      { heading: "9. Security & updates", paragraphs: ["Appropriate TOMs (TLS, access control). This notice may be updated when processing changes."] },
    ],
  },
  agb: {
    slug: "agb",
    title: "Terms & Conditions (B2B)",
    intro: "Contract terms for consulting, development, automation and operations — business customers only.",
    updated: "2 August 2026",
    related: [...related.agb],
    sections: [
      { heading: "1. Scope", paragraphs: ["B2B only. Customer terms apply only if expressly accepted in text form."] },
      { heading: "2. Formation & scope of work", paragraphs: ["Quotes are non-binding unless stated. AI quote indications are non-binding. Contract via acceptance/confirmation."] },
      { heading: "3. Pricing", paragraphs: [`€${company.dayRate}/day net (up to eight hours). VAT extra; reverse charge may apply.`] },
      { heading: "4. Cooperation", paragraphs: ["Customer provides content, access and decisions in time."] },
      { heading: "5. AI-assisted delivery", paragraphs: ["AI tools accelerate work; human accountability remains. Special data/model constraints must be agreed upfront."] },
      { heading: "6. Acceptance", paragraphs: ["Material defects must be reported promptly. Immateral deviations do not block acceptance."] },
      { heading: "7. IP & open source", paragraphs: ["Agreed rights after full payment. Pre-existing tools/know-how remain with NeXify AI. OSS has its own licences."] },
      { heading: "8. Liability", paragraphs: ["Unlimited for intent, gross negligence, personal injury and mandatory law. Slight negligence: limited to foreseeable typical damage for cardinal duties."] },
      { heading: "9. Confidentiality & DPA", paragraphs: ["Mutual confidentiality. Art. 28 DPA where NeXify AI processes personal data on instruction."] },
      { heading: "10. Law & venue", paragraphs: ["Dutch law. Venue for merchants: Venlo, NL, where permitted."] },
    ],
  },
  avv: {
    slug: "avv",
    title: "Data Processing Agreement (Art. 28)",
    intro: "Structure of an Art. 28 GDPR DPA for customer projects. Not a substitute for the project-specific agreement.",
    updated: "2 August 2026",
    related: [...related.avv],
    sections: [
      { heading: "1. When required", paragraphs: ["When NeXify AI processes personal data solely on the customer's documented instructions."] },
      { heading: "2. Form & SCCs", paragraphs: ["Written/electronic (Art. 28(9)). EU SCCs (EU) 2021/915 and, where needed, transfer SCCs (EU) 2021/914."] },
      { heading: "3. Mandatory contents", bullets: ["Subject/duration", "Nature/purpose", "Data types & data subjects", "Instructions, confidentiality, TOMs", "Sub-processors, data-subject rights, incidents, deletion/return, audits"] },
      { heading: "4. Modules", bullets: ["Annex A processing description", "Annex B TOMs", "Annex C sub-processors", "Annex D contacts", "[BITTE ERGÄNZEN: Master-Liste Unterauftragsverarbeiter mit Rechtsname/Sitzland/SCC-Status]"] },
      { heading: "5. Contact", paragraphs: [`${company.email}`] },
    ],
  },
  widerruf: {
    slug: "widerruf",
    title: "Withdrawal notice",
    intro: "Statutory distance-selling withdrawal rights do not apply to NeXify AI's B2B contracts.",
    updated: "2 August 2026",
    related: [...related.widerruf],
    sections: [
      { heading: "1. No consumer contract", paragraphs: ["Contracts only with businesses. Consumer withdrawal rights generally do not apply."] },
      { heading: "2. Exception", paragraphs: ["If a consumer contract were requested contrary to this policy, it must be disclosed before contracting; otherwise the contract is declined or individually briefed."] },
      { heading: "3. Goodwill (B2B)", paragraphs: ["Before work starts, written cancellation may be free of charge if no services were delivered. Delivered work is billed proportionally."] },
    ],
  },
  "cookie-richtlinie": {
    slug: "cookie-richtlinie",
    title: "Cookie Policy",
    intro: "Cookies/storage under § 25 TDDDG and GDPR — categories match the cookie banner: Necessary, Analytics, Marketing.",
    updated: "2 August 2026",
    related: [...related["cookie-richtlinie"]],
    sections: [
      { heading: "1. Legal basis", paragraphs: ["Strictly necessary storage without consent (§ 25(2) TDDDG). Other categories require prior consent."] },
      { heading: "2. Categories", subsections: [
        { heading: "2.1 Necessary (always on)", paragraphs: ["Language, session, security, consent store."] },
        { heading: "2.2 Analytics (opt-in)", paragraphs: ["Currently not deployed."] },
        { heading: "2.3 Marketing (opt-in)", paragraphs: ["Currently not deployed."] },
      ]},
      { heading: "3. Concrete storage", bullets: ["nexify-lang", "nexify-consent", "nova-greeted", "chat session id", "portal login cookie when used"] },
      { heading: "4. Browser & withdraw", paragraphs: ["Change via Cookie settings in the footer; browser deletion possible."] },
    ],
  },
  "ki-hinweise": {
    slug: "ki-hinweise",
    title: "AI Notice",
    intro: "Transparency for AI-assisted work and the on-site AI advisor (Art. 50 AI Act; Art. 22 GDPR).",
    updated: "2 August 2026",
    related: [...related["ki-hinweise"]],
    sections: [
      { heading: "1. You are interacting with AI", paragraphs: ["The NeXify AI advisor is an AI system. Binding offers are confirmed only by a human."] },
      { heading: "2. No solely automated decisions", paragraphs: ["No Art. 22 GDPR decisions with legal or similarly significant effects."] },
      { heading: "3. Data & training", paragraphs: ["Chat logs per Privacy Policy. No deliberate release for general model training without agreement."] },
      { heading: "4. Synthetic content", paragraphs: ["Art. 50(2) marking considered project-specifically where applicable."] },
    ],
  },
};
